// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("WebApplication2.Models.Klienci", b =>
                {
                    b.Property<int>("IdKlienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdKlienta");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("WebApplication2.Models.Rowery", b =>
                {
                    b.Property<int>("IdRoweru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amortyzacja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Hamulce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Napęd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RozmiarRamy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypRoweru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRoweru");

                    b.ToTable("Rowery");
                });

            modelBuilder.Entity("WebApplication2.Models.Wypozyczenia", b =>
                {
                    b.Property<int>("IdWypozyczenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataZwrotu")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdKlienta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRoweru")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KosztWypozyczenia")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdWypozyczenia");

                    b.HasIndex("IdKlienta");

                    b.HasIndex("IdRoweru");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("WebApplication2.Models.Wypozyczenia", b =>
                {
                    b.HasOne("WebApplication2.Models.Klienci", "Klient")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("IdKlienta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Models.Rowery", "Rower")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("IdRoweru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Rower");
                });

            modelBuilder.Entity("WebApplication2.Models.Klienci", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("WebApplication2.Models.Rowery", b =>
                {
                    b.Navigation("Wypozyczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
